#! /bin/sh

set -e

# Source debconf library.
. /usr/share/debconf/confmodule

if [ -d /sys/devices/system/cpu/cpu0/cpufreq ] || 
   [ -f /proc/cpufreq ] ; 
  then
    
    if !([ -d /proc/pmu ] || [ -f /proc/apm ] || [ -d /proc/acpi ]) ; then
      # debconf
      # warn the user about not being able
      # to determine PM driver to use
      db_input medium cpufreqd/no_pm || true
      db_go || true
    fi

else

  # debconf
  # warn the user about not being able
  # to determine cpufreq interface
  db_input medium cpufreqd/no_procfs_sysfs || true
  db_go || true

fi

exit 0 
